default: 
  dbfile: devices.db
  mqtt: 
    server: localhost
    #user: username
    #password: password
    base_topic: xiaomi 
  serial: 
    port: /dev/ttyACM0
  zigbee:
    bridge: "bridge"
  #Battery as voltage or percentage
  battery: voltage
